In [4]:
import pandas as pd 
from matplotlib import pyplot as plt
from pymongo import MongoClient

In [5]:
data = pd.read_csv('/Users/geyne/Desktop/global-master-2/Project_3_Team5-main/data_sets/homicides_by_age/EDADESNew.csv',encoding='cp1252')
data

,Year,Total,less than 1 year,1-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,30-34 years,...,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,85 years y mâ€¡s,No especificado,Unnamed: 22
0,1990.0,"14,493",143.0,181.0,180.0,275.0,"1,427","2,291","2,154","1,656",...,666,564,412.0,314.0,186.0,145.0,91.0,127.0,244,NaN
1,1991.0,"15,128",143.0,209.0,185.0,290.0,"1,606","2,575","2,243","1,725",...,651,531,438.0,316.0,215.0,137.0,98.0,78.0,273,NaN
2,1992.0,"16,594",122.0,204.0,150.0,265.0,"1,705","2,987","2,474","2,079",...,744,568,433.0,287.0,197.0,136.0,83.0,83.0,261,NaN
3,1993.0,"16,040",112.0,189.0,145.0,265.0,"1,643","2,740","2,518","1,913",...,702,583,390.0,289.0,248.0,130.0,82.0,100.0,239,NaN
4,1994.0,"15,839",115.0,192.0,138.0,254.0,"1,615","2,824","2,340","1,927",...,696,573,440.0,309.0,210.0,131.0,90.0,82.0,305,NaN
5,1995.0,"15,612",140.0,149.0,123.0,249.0,"1,550","2,665","2,458","1,865",...,687,561,368.0,292.0,199.0,120.0,84.0,87.0,274,NaN
6,1996.0,"14,505",129.0,169.0,126.0,213.0,"1,517","2,396","2,237","1,821",...,608,490,371.0,277.0,221.0,113.0,73.0,65.0,255,NaN
7,1997.0,"13,552",109.0,126.0,103.0,209.0,"1,412","2,259","2,004","1,631",...,584,489,374.0,275.0,177.0,141.0,71.0,79.0,251,NaN
8,1998.0,"13,656",81.0,137.0,127.0,233.0,"1,286","2,149","2,083","1,639",...,593,491,386.0,278.0,199.0,129.0,67.0,94.0,267,NaN
9,1999.0,"12,249",98.0,138.0,113.0,219.0,"1,140","1,703","1,854","1,592",...,586,447,306.0,245.0,200.0,132.0,75.0,84.0,217,NaN
10,2000.0,"10,737",79.0,108.0,93.0,197.0,973,"1,554","1,577","1,362",...,488,419,315.0,233.0,169.0,132.0,59.0,79.0,151,NaN
11,2001.0,"10,285",80.0,120.0,99.0,198.0,981,"1,528","1,495","1,226",...,494,358,270.0,226.0,194.0,118.0,66.0,60.0,143,NaN
12,2002.0,"10,088",83.0,114.0,69.0,164.0,944,"1,423","1,411","1,256",...,470,412,294.0,216.0,163.0,110.0,73.0,80.0,173,NaN
13,2003.0,"10,087",71.0,105.0,68.0,158.0,860,"1,292","1,455","1,333",...,517,404,274.0,232.0,167.0,119.0,97.0,76.0,181,NaN
14,2004.0,"9,329",79.0,86.0,56.0,146.0,777,"1,262","1,278","1,238",...,474,376,259.0,210.0,154.0,104.0,81.0,67.0,116,NaN
15,2005.0,"9,921",69.0,108.0,75.0,182.0,814,"1,313","1,382","1,284",...,515,395,320.0,220.0,157.0,119.0,63.0,73.0,184,NaN
16,2006.0,"10,452",67.0,112.0,66.0,159.0,849,"1,312","1,410","1,453",...,559,399,301.0,228.0,191.0,111.0,62.0,69.0,199,NaN
17,2007.0,"8,867",63.0,63.0,57.0,115.0,704,"1,081","1,192","1,235",...,512,346,238.0,166.0,155.0,78.0,51.0,43.0,152,NaN
18,2008.0,"14,006",71.0,84.0,50.0,140.0,"1,109","1,894","2,066","2,160",...,659,427,352.0,239.0,176.0,107.0,69.0,57.0,218,NaN
19,2009.0,"19,803",105.0,127.0,82.0,184.0,"1,577","2,766","3,005","2,824",...,925,631,423.0,301.0,203.0,134.0,81.0,74.0,528,NaN
20,2010.0,"25,757",60.0,123.0,65.0,194.0,"2,234","3,812","4,125","4,052",...,"1,096",688,441.0,317.0,240.0,142.0,69.0,78.0,731,NaN
21,2011.0,"27,213",66.0,100.0,95.0,235.0,"2,419","3,926","4,190","3,800",...,"1,141",738,501.0,341.0,221.0,149.0,98.0,115.0,"1,740",NaN
22,2012.0,"25,967",73.0,119.0,76.0,249.0,"2,413","3,870","3,792","3,506",...,"1,095",728,513.0,358.0,255.0,191.0,85.0,81.0,"1,657",NaN
23,2013.0,"23,063",84.0,123.0,79.0,181.0,"1,828","3,277","3,314","3,117",...,"1,063",731,543.0,366.0,282.0,170.0,110.0,108.0,"1,234",NaN
24,2014.0,"20,010",80.0,111.0,68.0,151.0,"1,477","2,721","2,728","2,679",...,958,666,438.0,366.0,220.0,166.0,108.0,101.0,"1,274",NaN
25,2015.0,"20,762",68.0,102.0,73.0,144.0,"1,561","2,845","2,943","2,688",...,"1,052",750,495.0,344.0,225.0,167.0,102.0,71.0,"1,081",NaN
26,2016.0,"24,559",52.0,76.0,71.0,194.0,"1,770","3,470","3,618","3,257",...,"1,268",869,577.0,365.0,240.0,148.0,101.0,80.0,"1,282",NaN
27,2017.0,"32,079",51.0,101.0,69.0,234.0,"2,403","4,626","4,857","4,548",...,"1,499","1,019",646.0,455.0,294.0,189.0,99.0,58.0,"1,433",NaN
28,2018.0,"36,685",78.0,104.0,92.0,193.0,"2,562","5,069","5,649","5,058",...,"1,769","1,094",667.0,418.0,255.0,163.0,87.0,77.0,"2,374",NaN
29,2019.0,"36,661",72.0,103.0,83.0,203.0,"2,452","5,194","5,956","5,327",...,"1,738","1,120",710.0,418.0,269.0,159.0,96.0,67.0,"1,831",NaN
30,2020.0,"36,773",55.0,97.0,92.0,212.0,"2,362","5,083","5,650","4,969",...,"1,754","1,125",852.0,401.0,252.0,166.0,126.0,102.0,"3,075",NaN
31,2021.0,"35,700",61.0,73.0,89.0,220.0,"2,290","4,947","5,358","4,997",...,"1,752","1,035",679.0,436.0,256.0,138.0,82.0,81.0,"2,898",NaN
32,2022.0,"33,287",64.0,71.0,78.0,199.0,"2,274","4,259","4,912","4,583",...,"1,671","1,068",651.0,385.0,235.0,163.0,90.0,94.0,"2,901",NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data = data.drop(columns=['Unnamed: 22'])
data

,Year,Total,less than 1 year,1-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,30-34 years,...,45-49 years,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,85 years y mâ€¡s,No especificado
0,1990.0,"14,493",143.0,181.0,180.0,275.0,"1,427","2,291","2,154","1,656",...,932,666,564,412.0,314.0,186.0,145.0,91.0,127.0,244
1,1991.0,"15,128",143.0,209.0,185.0,290.0,"1,606","2,575","2,243","1,725",...,898,651,531,438.0,316.0,215.0,137.0,98.0,78.0,273
2,1992.0,"16,594",122.0,204.0,150.0,265.0,"1,705","2,987","2,474","2,079",...,942,744,568,433.0,287.0,197.0,136.0,83.0,83.0,261
3,1993.0,"16,040",112.0,189.0,145.0,265.0,"1,643","2,740","2,518","1,913",...,936,702,583,390.0,289.0,248.0,130.0,82.0,100.0,239
4,1994.0,"15,839",115.0,192.0,138.0,254.0,"1,615","2,824","2,340","1,927",...,940,696,573,440.0,309.0,210.0,131.0,90.0,82.0,305
5,1995.0,"15,612",140.0,149.0,123.0,249.0,"1,550","2,665","2,458","1,865",...,916,687,561,368.0,292.0,199.0,120.0,84.0,87.0,274
6,1996.0,"14,505",129.0,169.0,126.0,213.0,"1,517","2,396","2,237","1,821",...,942,608,490,371.0,277.0,221.0,113.0,73.0,65.0,255
7,1997.0,"13,552",109.0,126.0,103.0,209.0,"1,412","2,259","2,004","1,631",...,794,584,489,374.0,275.0,177.0,141.0,71.0,79.0,251
8,1998.0,"13,656",81.0,137.0,127.0,233.0,"1,286","2,149","2,083","1,639",...,874,593,491,386.0,278.0,199.0,129.0,67.0,94.0,267
9,1999.0,"12,249",98.0,138.0,113.0,219.0,"1,140","1,703","1,854","1,592",...,752,586,447,306.0,245.0,200.0,132.0,75.0,84.0,217
10,2000.0,"10,737",79.0,108.0,93.0,197.0,973,"1,554","1,577","1,362",...,724,488,419,315.0,233.0,169.0,132.0,59.0,79.0,151
11,2001.0,"10,285",80.0,120.0,99.0,198.0,981,"1,528","1,495","1,226",...,663,494,358,270.0,226.0,194.0,118.0,66.0,60.0,143
12,2002.0,"10,088",83.0,114.0,69.0,164.0,944,"1,423","1,411","1,256",...,698,470,412,294.0,216.0,163.0,110.0,73.0,80.0,173
13,2003.0,"10,087",71.0,105.0,68.0,158.0,860,"1,292","1,455","1,333",...,728,517,404,274.0,232.0,167.0,119.0,97.0,76.0,181
14,2004.0,"9,329",79.0,86.0,56.0,146.0,777,"1,262","1,278","1,238",...,598,474,376,259.0,210.0,154.0,104.0,81.0,67.0,116
15,2005.0,"9,921",69.0,108.0,75.0,182.0,814,"1,313","1,382","1,284",...,682,515,395,320.0,220.0,157.0,119.0,63.0,73.0,184
16,2006.0,"10,452",67.0,112.0,66.0,159.0,849,"1,312","1,410","1,453",...,724,559,399,301.0,228.0,191.0,111.0,62.0,69.0,199
17,2007.0,"8,867",63.0,63.0,57.0,115.0,704,"1,081","1,192","1,235",...,656,512,346,238.0,166.0,155.0,78.0,51.0,43.0,152
18,2008.0,"14,006",71.0,84.0,50.0,140.0,"1,109","1,894","2,066","2,160",...,"1,006",659,427,352.0,239.0,176.0,107.0,69.0,57.0,218
19,2009.0,"19,803",105.0,127.0,82.0,184.0,"1,577","2,766","3,005","2,824",...,"1,281",925,631,423.0,301.0,203.0,134.0,81.0,74.0,528
20,2010.0,"25,757",60.0,123.0,65.0,194.0,"2,234","3,812","4,125","4,052",...,"1,606","1,096",688,441.0,317.0,240.0,142.0,69.0,78.0,731
21,2011.0,"27,213",66.0,100.0,95.0,235.0,"2,419","3,926","4,190","3,800",...,"1,603","1,141",738,501.0,341.0,221.0,149.0,98.0,115.0,"1,740"
22,2012.0,"25,967",73.0,119.0,76.0,249.0,"2,413","3,870","3,792","3,506",...,"1,571","1,095",728,513.0,358.0,255.0,191.0,85.0,81.0,"1,657"
23,2013.0,"23,063",84.0,123.0,79.0,181.0,"1,828","3,277","3,314","3,117",...,"1,564","1,063",731,543.0,366.0,282.0,170.0,110.0,108.0,"1,234"
24,2014.0,"20,010",80.0,111.0,68.0,151.0,"1,477","2,721","2,728","2,679",...,"1,404",958,666,438.0,366.0,220.0,166.0,108.0,101.0,"1,274"
25,2015.0,"20,762",68.0,102.0,73.0,144.0,"1,561","2,845","2,943","2,688",...,"1,483","1,052",750,495.0,344.0,225.0,167.0,102.0,71.0,"1,081"
26,2016.0,"24,559",52.0,76.0,71.0,194.0,"1,770","3,470","3,618","3,257",...,"1,684","1,268",869,577.0,365.0,240.0,148.0,101.0,80.0,"1,282"
27,2017.0,"32,079",51.0,101.0,69.0,234.0,"2,403","4,626","4,857","4,548",...,"2,233","1,499","1,019",646.0,455.0,294.0,189.0,99.0,58.0,"1,433"
28,2018.0,"36,685",78.0,104.0,92.0,193.0,"2,562","5,069","5,649","5,058",...,"2,686","1,769","1,094",667.0,418.0,255.0,163.0,87.0,77.0,"2,374"
29,2019.0,"36,661",72.0,103.0,83.0,203.0,"2,452","5,194","5,956","5,327",...,"2,756","1,738","1,120",710.0,418.0,269.0,159.0,96.0,67.0,"1,831"
30,2020.0,"36,773",55.0,97.0,92.0,212.0,"2,362","5,083","5,650","4,969",...,"2,627","1,754","1,125",852.0,401.0,252.0,166.0,126.0,102.0,"3,075"
31,2021.0,"35,700",61.0,73.0,89.0,220.0,"2,290","4,947","5,358","4,997",...,"2,625","1,752","1,035",679.0,436.0,256.0,138.0,82.0,81.0,"2,898"
32,2022.0,"33,287",64.0,71.0,78.0,199.0,"2,274","4,259","4,912","4,583",...,"2,467","1,671","1,068",651.0,385.0,235.0,163.0,90.0,94.0,"2,901"
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data = data.dropna()
data

Empty DataFrame
Columns: [Year, Total, less than 1 year, 1-4 years, 5-9 years, 10-14 years, 15-19 years, 20-24 years, 25-29 years, 30-34 years, 35-39 years, 40-44 years, 45-49 years, 50-54 years, 55-59 years, 60-64 years, 65-69 years, 70-74 years, 75-79 years, 80-84 years, 85 years y mâ€¡s, No especificado, Unnamed: 22]
Index: []

[0 rows x 23 columns]

In [8]:
columns = list(data.columns)
columns

['Year',
 'Total',
 'less than 1 year',
 '1-4 years',
 '5-9 years',
 '10-14 years',
 '15-19 years',
 '20-24 years',
 '25-29 years',
 '30-34 years',
 '35-39 years',
 '40-44 years',
 '45-49 years',
 '50-54 years',
 '55-59 years',
 '60-64 years',
 '65-69 years',
 '70-74 years',
 '75-79 years',
 '80-84 years',
 '85 years y mâ€¡s',
 'No especificado']

In [9]:
#turning data into the correct dtype
data[columns] = data[columns].replace({',':''}, regex = True)
data[columns] = data[columns].astype('int')
data

/var/folders/fk/cvrcy451067_965x_wm3fkwc0000gn/T/ipykernel_93903/2752741138.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[columns] = data[columns].replace({',':''}, regex = True)
/var/folders/fk/cvrcy451067_965x_wm3fkwc0000gn/T/ipykernel_93903/2752741138.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[columns] = data[columns].astype('int')

,Year,Total,less than 1 year,1-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,30-34 years,...,45-49 years,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,85 years y mâ€¡s,No especificado
0,1990,14493,143,181,180,275,1427,2291,2154,1656,...,932,666,564,412,314,186,145,91,127,244
1,1991,15128,143,209,185,290,1606,2575,2243,1725,...,898,651,531,438,316,215,137,98,78,273
2,1992,16594,122,204,150,265,1705,2987,2474,2079,...,942,744,568,433,287,197,136,83,83,261
3,1993,16040,112,189,145,265,1643,2740,2518,1913,...,936,702,583,390,289,248,130,82,100,239
4,1994,15839,115,192,138,254,1615,2824,2340,1927,...,940,696,573,440,309,210,131,90,82,305
5,1995,15612,140,149,123,249,1550,2665,2458,1865,...,916,687,561,368,292,199,120,84,87,274
6,1996,14505,129,169,126,213,1517,2396,2237,1821,...,942,608,490,371,277,221,113,73,65,255
7,1997,13552,109,126,103,209,1412,2259,2004,1631,...,794,584,489,374,275,177,141,71,79,251
8,1998,13656,81,137,127,233,1286,2149,2083,1639,...,874,593,491,386,278,199,129,67,94,267
9,1999,12249,98,138,113,219,1140,1703,1854,1592,...,752,586,447,306,245,200,132,75,84,217
10,2000,10737,79,108,93,197,973,1554,1577,1362,...,724,488,419,315,233,169,132,59,79,151
11,2001,10285,80,120,99,198,981,1528,1495,1226,...,663,494,358,270,226,194,118,66,60,143
12,2002,10088,83,114,69,164,944,1423,1411,1256,...,698,470,412,294,216,163,110,73,80,173
13,2003,10087,71,105,68,158,860,1292,1455,1333,...,728,517,404,274,232,167,119,97,76,181
14,2004,9329,79,86,56,146,777,1262,1278,1238,...,598,474,376,259,210,154,104,81,67,116
15,2005,9921,69,108,75,182,814,1313,1382,1284,...,682,515,395,320,220,157,119,63,73,184
16,2006,10452,67,112,66,159,849,1312,1410,1453,...,724,559,399,301,228,191,111,62,69,199
17,2007,8867,63,63,57,115,704,1081,1192,1235,...,656,512,346,238,166,155,78,51,43,152
18,2008,14006,71,84,50,140,1109,1894,2066,2160,...,1006,659,427,352,239,176,107,69,57,218
19,2009,19803,105,127,82,184,1577,2766,3005,2824,...,1281,925,631,423,301,203,134,81,74,528
20,2010,25757,60,123,65,194,2234,3812,4125,4052,...,1606,1096,688,441,317,240,142,69,78,731
21,2011,27213,66,100,95,235,2419,3926,4190,3800,...,1603,1141,738,501,341,221,149,98,115,1740
22,2012,25967,73,119,76,249,2413,3870,3792,3506,...,1571,1095,728,513,358,255,191,85,81,1657
23,2013,23063,84,123,79,181,1828,3277,3314,3117,...,1564,1063,731,543,366,282,170,110,108,1234
24,2014,20010,80,111,68,151,1477,2721,2728,2679,...,1404,958,666,438,366,220,166,108,101,1274
25,2015,20762,68,102,73,144,1561,2845,2943,2688,...,1483,1052,750,495,344,225,167,102,71,1081
26,2016,24559,52,76,71,194,1770,3470,3618,3257,...,1684,1268,869,577,365,240,148,101,80,1282
27,2017,32079,51,101,69,234,2403,4626,4857,4548,...,2233,1499,1019,646,455,294,189,99,58,1433
28,2018,36685,78,104,92,193,2562,5069,5649,5058,...,2686,1769,1094,667,418,255,163,87,77,2374
29,2019,36661,72,103,83,203,2452,5194,5956,5327,...,2756,1738,1120,710,418,269,159,96,67,1831
30,2020,36773,55,97,92,212,2362,5083,5650,4969,...,2627,1754,1125,852,401,252,166,126,102,3075
31,2021,35700,61,73,89,220,2290,4947,5358,4997,...,2625,1752,1035,679,436,256,138,82,81,2898
32,2022,33287,64,71,78,199,2274,4259,4912,4583,...,2467,1671,1068,651,385,235,163,90,94,2901

In [10]:
data = data.drop(columns=['No especificado'])
data

,Year,Total,less than 1 year,1-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,30-34 years,...,40-44 years,45-49 years,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,85 years y mâ€¡s
0,1990,14493,143,181,180,275,1427,2291,2154,1656,...,1032,932,666,564,412,314,186,145,91,127
1,1991,15128,143,209,185,290,1606,2575,2243,1725,...,1050,898,651,531,438,316,215,137,98,78
2,1992,16594,122,204,150,265,1705,2987,2474,2079,...,1206,942,744,568,433,287,197,136,83,83
3,1993,16040,112,189,145,265,1643,2740,2518,1913,...,1145,936,702,583,390,289,248,130,82,100
4,1994,15839,115,192,138,254,1615,2824,2340,1927,...,1116,940,696,573,440,309,210,131,90,82
5,1995,15612,140,149,123,249,1550,2665,2458,1865,...,1178,916,687,561,368,292,199,120,84,87
6,1996,14505,129,169,126,213,1517,2396,2237,1821,...,1025,942,608,490,371,277,221,113,73,65
7,1997,13552,109,126,103,209,1412,2259,2004,1631,...,1048,794,584,489,374,275,177,141,71,79
8,1998,13656,81,137,127,233,1286,2149,2083,1639,...,1096,874,593,491,386,278,199,129,67,94
9,1999,12249,98,138,113,219,1140,1703,1854,1592,...,984,752,586,447,306,245,200,132,75,84
10,2000,10737,79,108,93,197,973,1554,1577,1362,...,864,724,488,419,315,233,169,132,59,79
11,2001,10285,80,120,99,198,981,1528,1495,1226,...,836,663,494,358,270,226,194,118,66,60
12,2002,10088,83,114,69,164,944,1423,1411,1256,...,855,698,470,412,294,216,163,110,73,80
13,2003,10087,71,105,68,158,860,1292,1455,1333,...,880,728,517,404,274,232,167,119,97,76
14,2004,9329,79,86,56,146,777,1262,1278,1238,...,896,598,474,376,259,210,154,104,81,67
15,2005,9921,69,108,75,182,814,1313,1382,1284,...,874,682,515,395,320,220,157,119,63,73
16,2006,10452,67,112,66,159,849,1312,1410,1453,...,971,724,559,399,301,228,191,111,62,69
17,2007,8867,63,63,57,115,704,1081,1192,1235,...,860,656,512,346,238,166,155,78,51,43
18,2008,14006,71,84,50,140,1109,1894,2066,2160,...,1344,1006,659,427,352,239,176,107,69,57
19,2009,19803,105,127,82,184,1577,2766,3005,2824,...,1829,1281,925,631,423,301,203,134,81,74
20,2010,25757,60,123,65,194,2234,3812,4125,4052,...,2309,1606,1096,688,441,317,240,142,69,78
21,2011,27213,66,100,95,235,2419,3926,4190,3800,...,2366,1603,1141,738,501,341,221,149,98,115
22,2012,25967,73,119,76,249,2413,3870,3792,3506,...,2293,1571,1095,728,513,358,255,191,85,81
23,2013,23063,84,123,79,181,1828,3277,3314,3117,...,2142,1564,1063,731,543,366,282,170,110,108
24,2014,20010,80,111,68,151,1477,2721,2728,2679,...,1952,1404,958,666,438,366,220,166,108,101
25,2015,20762,68,102,73,144,1561,2845,2943,2688,...,2098,1483,1052,750,495,344,225,167,102,71
26,2016,24559,52,76,71,194,1770,3470,3618,3257,...,2487,1684,1268,869,577,365,240,148,101,80
27,2017,32079,51,101,69,234,2403,4626,4857,4548,...,3293,2233,1499,1019,646,455,294,189,99,58
28,2018,36685,78,104,92,193,2562,5069,5649,5058,...,3745,2686,1769,1094,667,418,255,163,87,77
29,2019,36661,72,103,83,203,2452,5194,5956,5327,...,3693,2756,1738,1120,710,418,269,159,96,67
30,2020,36773,55,97,92,212,2362,5083,5650,4969,...,3529,2627,1754,1125,852,401,252,166,126,102
31,2021,35700,61,73,89,220,2290,4947,5358,4997,...,3421,2625,1752,1035,679,436,256,138,82,81
32,2022,33287,64,71,78,199,2274,4259,4912,4583,...,3218,2467,1671,1068,651,385,235,163,90,94

In [11]:
df1 = data[data['Year'] > 2017]
df1 = df1.reset_index()
df1

,index,Year,Total,less than 1 year,1-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,...,40-44 years,45-49 years,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,85 years y mâ€¡s
0,28,2018,36685,78,104,92,193,2562,5069,5649,...,3745,2686,1769,1094,667,418,255,163,87,77
1,29,2019,36661,72,103,83,203,2452,5194,5956,...,3693,2756,1738,1120,710,418,269,159,96,67
2,30,2020,36773,55,97,92,212,2362,5083,5650,...,3529,2627,1754,1125,852,401,252,166,126,102
3,31,2021,35700,61,73,89,220,2290,4947,5358,...,3421,2625,1752,1035,679,436,256,138,82,81
4,32,2022,33287,64,71,78,199,2274,4259,4912,...,3218,2467,1671,1068,651,385,235,163,90,94

In [12]:
df1 = df1.drop(columns=['index'])

In [13]:
df1

,Year,Total,less than 1 year,1-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,30-34 years,...,40-44 years,45-49 years,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,85 years y mâ€¡s
0,2018,36685,78,104,92,193,2562,5069,5649,5058,...,3745,2686,1769,1094,667,418,255,163,87,77
1,2019,36661,72,103,83,203,2452,5194,5956,5327,...,3693,2756,1738,1120,710,418,269,159,96,67
2,2020,36773,55,97,92,212,2362,5083,5650,4969,...,3529,2627,1754,1125,852,401,252,166,126,102
3,2021,35700,61,73,89,220,2290,4947,5358,4997,...,3421,2625,1752,1035,679,436,256,138,82,81
4,2022,33287,64,71,78,199,2274,4259,4912,4583,...,3218,2467,1671,1068,651,385,235,163,90,94

In [14]:
df1.to_csv('./newDataAge.csv')

In [3]:
df1

NameError: name 'df1' is not defined